services:
  app:
    image: gradle:8.10.2-jdk21
    working_dir: /home/gradle/project
    volumes:
      - ./:/home/gradle/project
      - gradle-cache:/home/gradle/.gradle
    command: ["gradle", "bootRun"]
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=default

volumes:
  gradle-cache:
