name: CI

on:
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Normalize Gradle wrapper (LF + exec permission)
        run: |
          git config core.autocrlf false
          sed -i 's/\r$//' gradlew
          chmod +x gradlew
          ls -l gradlew
          file gradlew

      - name: Validate Gradle wrapper (retry)
        uses: Wandalen/wretry.action@v1.4.9
        with:
          action: gradle/wrapper-validation-action@v2
          attempt_limit: 3
          attempt_delay: 5000

      - name: Validate Gradle wrapper (soft-fail fallback)
        if: failure()
        continue-on-error: true
        uses: gradle/wrapper-validation-action@v2

      - name: Build and test
        run: bash ./gradlew --no-daemon clean test

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            **/build/reports/tests/test
            **/build/test-results/test
