name: Protect Branches (Disallow Direct Pushes)

on:
  push:
    branches:
      - master
      - develop

permissions:
  contents: read
  pull-requests: read

jobs:
  enforce-pr-only:
    name: Enforce PR-only updates to protected branches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate push source
        shell: bash
        env:
          GH_OWNER: ${{ github.repository_owner }}
          GH_REPO: ${{ github.event.repository.name }}
          GH_SHA: ${{ github.sha }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Pusher: ${{ github.actor }}"
          # Allow pushes from the github-actions bot (used by other workflows)
          if [[ "${{ github.actor }}" == "github-actions[bot]" ]]; then
            echo "Push is from github-actions bot. Allowing."
            exit 0
          fi

          echo "Ref: $GITHUB_REF"
          echo "SHA: $GH_SHA"
          echo "Head message: '${{ github.event.head_commit.message }}'"

          # Check via GitHub API whether this commit is associated with a Pull Request (supports merge/squash/rebase merges)
          prs_json=$(curl -sSL -H "Authorization: Bearer $TOKEN" -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/repos/$GH_OWNER/$GH_REPO/commits/$GH_SHA/pulls")
          pr_count=$(echo "$prs_json" | jq 'length')
          echo "Associated PR count for this commit: $pr_count"
          if [[ "$pr_count" -gt 0 ]]; then
            echo "This push is associated with a Pull Request merge. Allowing."
            exit 0
          fi

          echo "::error::Direct pushes to '${{ github.ref_name }}' are not allowed. Please use a Pull Request."
          echo "::notice::If you performed a squash merge with a custom message, this check now uses the GitHub API to detect PR associations; if it still fails, ensure the PR merge completed successfully."
          exit 1
