name: Protect Branches (Disallow Direct Pushes)

on:
  push:
    branches:
      - master
      - develop

jobs:
  enforce-pr-only:
    name: Enforce PR-only updates to protected branches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate push source
        shell: bash
        run: |
          echo "Pusher: ${{ github.actor }}"
          # Allow pushes from the github-actions bot (used by other workflows)
          if [[ "${{ github.actor }}" == "github-actions[bot]" ]]; then
            echo "Push is from github-actions bot. Allowing."
            exit 0
          fi

          echo "Ref: $GITHUB_REF"
          echo "SHA: $GITHUB_SHA"
          echo "Head message: '${{ github.event.head_commit.message }}'"

          # Determine parent count (merge commits have >= 2 parents)
          parent_count=$(git show -s --format=%P "$GITHUB_SHA" | wc -w)
          echo "Parent count: $parent_count"

          # Heuristics to detect PR merges:
          # 1) Merge commit created by the default merge strategy (message contains 'Merge pull request')
          # 2) Squash merge default message often contains '(#<number>)'
          # 3) Parent count >= 2 (non-squash merge commit)
          head_msg='${{ github.event.head_commit.message }}'
          if [[ "$head_msg" == *"Merge pull request"* ]] || [[ "$head_msg" =~ \(\\#([0-9]+)\) ]] || [[ "$parent_count" -ge 2 ]]; then
            echo "This push appears to be the result of a Pull Request merge. Allowing."
            exit 0
          fi

          echo "::error::Direct pushes to '${{ github.ref_name }}' are not allowed. Please use a Pull Request."
          echo "::notice::To prevent direct pushes entirely, enable Branch Protection Rules in your repository settings and require this check to pass before merging."
          exit 1
