name: Release Publish

on:
  push:
    branches:
      - master

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Compute next release version
        id: ver
        shell: bash
        run: |
          last_tag=$(git tag -l 'v*' | sort -V | tail -n1)
          if [ -z "$last_tag" ]; then
            base="0.0.1"
          else
            ver=${last_tag#v}
            IFS='.' read -r major minor patch <<<"$ver"
            patch=$((patch+1))
            base="$major.$minor.$patch"
          fi
          echo "base=$base" >> $GITHUB_OUTPUT
          echo "PROJECT_VERSION=$base" >> $GITHUB_ENV
          echo "Next release: $base"

      - name: Ensure gradlew is executable
        run: chmod +x gradlew

      - name: Build and test
        run: ./gradlew --no-daemon clean test

      - name: Publish release to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew --no-daemon publish

      - name: Create Git tag
        env:
          PROJECT_VERSION: ${{ env.PROJECT_VERSION }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag "v${PROJECT_VERSION}"
          git push origin "v${PROJECT_VERSION}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.PROJECT_VERSION }}
          name: v${{ env.PROJECT_VERSION }}
          draft: false
          prerelease: false
